//! クエリファイル保存フォルダに置く、接続を説明するメタファイルの生成。
//!
//! 各接続のクエリファイルは `<sqlfiles_dir>/<folder>/*.sql` に保存される。
//! AI エージェント (sql-agent 系や coding agent) や人間がそのフォルダを開いた
//! 時に「どの DB のどんな用途のクエリか」を理解できるよう、接続の非機密メタ
//! 情報を Markdown で書き出す。
//!
//! 機密 (パスワード・SSH 鍵・パスフレーズ) は絶対に含めない。含めるのは
//! ConnectionInfo でフロントに既に渡している範囲の情報 (name / description /
//! engine / host / port / schema / user / readonly / group / SSH トンネルの
//! 有無) に留める。

use std::fs;
use std::path::Path;

use crate::config::ServerConfig;
use crate::error::AppError;

/// メタファイル名。`.sql` ではないためクエリファイル一覧・検索 (.sql のみ対象)
/// には現れない。dot 始まりでもないためエージェント/Finder から可視。
pub const META_FILE_NAME: &str = "_queryfolio.md";

/// Option<String> を表示用に整形する (None / 空白のみは "-")。
fn field(value: Option<&str>) -> String {
    match value.map(str::trim) {
        Some(v) if !v.is_empty() => v.to_string(),
        _ => "-".to_string(),
    }
}

/// 接続の非機密メタ情報から Markdown を生成する。
pub fn render_meta(server: &ServerConfig) -> String {
    let mut out = String::new();
    out.push_str(&format!("# QueryFolio — {}\n\n", server.name));

    if let Some(desc) = server.description.as_deref() {
        let desc = desc.trim();
        if !desc.is_empty() {
            out.push_str(desc);
            out.push_str("\n\n");
        }
    }

    out.push_str(
        "This file is auto-generated by QueryFolio and describes the database \
connection whose SQL query files are stored in this folder. It exists so that \
AI agents and humans can understand what these queries target. Manual edits are \
overwritten. No secrets (passwords, SSH keys) are included.\n\n",
    );

    out.push_str(&format!("- **Connection:** {}\n", server.name));
    out.push_str(&format!("- **Engine:** {}\n", server.engine));
    out.push_str(&format!("- **Host:** {}\n", field(server.host.as_deref())));
    out.push_str(&format!(
        "- **Port:** {}\n",
        server.port.map(|p| p.to_string()).unwrap_or_else(|| "-".into())
    ));
    out.push_str(&format!(
        "- **Database (schema):** {}\n",
        field(server.schema.as_deref())
    ));
    out.push_str(&format!("- **User:** {}\n", field(server.user.as_deref())));
    out.push_str(&format!(
        "- **Read-only:** {}\n",
        if server.readonly { "yes" } else { "no" }
    ));
    out.push_str(&format!(
        "- **Group:** {}\n",
        field(server.group_name.as_deref())
    ));

    let ssh = match server.ssh_tunnel.as_ref() {
        Some(t) => format!("via {}@{}:{}", t.user, t.host, t.port),
        None => "no".to_string(),
    };
    out.push_str(&format!("- **SSH tunnel:** {ssh}\n"));

    out
}

/// フォルダにメタファイルを書き出す。
///
/// - フォルダが存在しない時は何もしない (メタだけのために空フォルダを作らない)。
/// - 内容が既存と同じなら書かない (mtime churn 回避)。
pub fn write_folder_meta(dir: &Path, server: &ServerConfig) -> Result<(), AppError> {
    if !dir.is_dir() {
        return Ok(());
    }
    let content = render_meta(server);
    let path = dir.join(META_FILE_NAME);
    if let Ok(existing) = fs::read_to_string(&path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(&path, content)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn base_server() -> ServerConfig {
        ServerConfig {
            name: "prod-db".to_string(),
            description: Some("Production orders database".to_string()),
            folder_name: None,
            engine: "postgres".to_string(),
            host: Some("db.example.com".to_string()),
            port: Some(5432),
            schema: Some("orders".to_string()),
            user: Some("app".to_string()),
            password: Some("s3cret".to_string()),
            ssh_tunnel: None,
            readonly: true,
            allow_dangerous_statements: false,
            group_name: Some("Production".to_string()),
        }
    }

    #[test]
    fn test_render_meta_contains_fields_and_no_secret() {
        let meta = render_meta(&base_server());
        assert!(meta.contains("# QueryFolio — prod-db"));
        assert!(meta.contains("Production orders database"));
        assert!(meta.contains("- **Engine:** postgres"));
        assert!(meta.contains("- **Host:** db.example.com"));
        assert!(meta.contains("- **Port:** 5432"));
        assert!(meta.contains("- **Database (schema):** orders"));
        assert!(meta.contains("- **User:** app"));
        assert!(meta.contains("- **Read-only:** yes"));
        assert!(meta.contains("- **Group:** Production"));
        assert!(meta.contains("- **SSH tunnel:** no"));
        // パスワードは絶対に含めない
        assert!(!meta.contains("s3cret"));
    }

    #[test]
    fn test_render_meta_optional_fields_dash() {
        let mut s = base_server();
        s.description = None;
        s.host = None;
        s.port = None;
        s.schema = Some("   ".to_string());
        s.user = None;
        s.readonly = false;
        s.group_name = None;
        let meta = render_meta(&s);
        assert!(meta.contains("- **Host:** -"));
        assert!(meta.contains("- **Port:** -"));
        assert!(meta.contains("- **Database (schema):** -"));
        assert!(meta.contains("- **User:** -"));
        assert!(meta.contains("- **Read-only:** no"));
        assert!(meta.contains("- **Group:** -"));
    }

    #[test]
    fn test_render_meta_ssh_tunnel_without_credentials() {
        let mut s = base_server();
        s.ssh_tunnel = Some(crate::config::SshTunnelConfig {
            host: "bastion.example.com".to_string(),
            port: 22,
            user: "tunnel".to_string(),
            password: Some("tunnelpass".to_string()),
            private_key_path: Some("/home/me/.ssh/id_ed25519".to_string()),
            private_key_passphrase: Some("keypass".to_string()),
            identity_agent: None,
        });
        let meta = render_meta(&s);
        assert!(meta.contains("- **SSH tunnel:** via tunnel@bastion.example.com:22"));
        // トンネルの機密も含めない
        assert!(!meta.contains("tunnelpass"));
        assert!(!meta.contains("keypass"));
        assert!(!meta.contains("id_ed25519"));
    }

    #[test]
    fn test_write_folder_meta_skips_missing_dir() {
        let dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-missing-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&dir);
        // フォルダが無ければ書かない (空フォルダも作らない)
        write_folder_meta(&dir, &base_server()).unwrap();
        assert!(!dir.exists());
    }

    #[test]
    fn test_meta_file_does_not_appear_in_query_file_listing() {
        // lib.rs のフロー (クエリファイル作成 → メタファイル書き出し) を再現し、
        // メタファイルがクエリファイル一覧・検索 (.sql のみ対象) に出ないことを確認する。
        use crate::query_files;

        let sqlfiles_dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-listing-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&sqlfiles_dir);
        let folder = "db.example.com_postgres_orders_app";

        // クエリファイルを 1 つ作る (フォルダが作られる)
        query_files::create_query_file(&sqlfiles_dir, folder, "report").unwrap();
        // メタファイルを書き出す (lib.rs の refresh_folder_meta 相当)
        let dir = query_files::connection_dir(&sqlfiles_dir, folder).unwrap();
        write_folder_meta(&dir, &base_server()).unwrap();

        // メタファイルは実在する
        assert!(dir.join(META_FILE_NAME).exists());
        // が、クエリファイル一覧には現れない (.sql のみ)
        let files = query_files::list_query_files(&sqlfiles_dir, folder).unwrap();
        assert_eq!(files, vec!["report.sql"]);
        // 検索にも現れない (中身の "Production" は base_server の group 名だが
        // メタファイルは .sql でないため検索対象外)
        let hits =
            query_files::search_query_files(&sqlfiles_dir, folder, "Production").unwrap();
        assert!(hits.is_empty());

        let _ = fs::remove_dir_all(&sqlfiles_dir);
    }

    #[test]
    fn test_write_folder_meta_writes_and_is_idempotent() {
        let dir = std::env::temp_dir().join(format!(
            "queryfolio-meta-write-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let server = base_server();
        write_folder_meta(&dir, &server).unwrap();
        let path = dir.join(META_FILE_NAME);
        assert!(path.exists());
        let written = fs::read_to_string(&path).unwrap();
        assert_eq!(written, render_meta(&server));

        // 内容が同じなら mtime を変えない (書き込みをスキップする)
        let mtime1 = fs::metadata(&path).unwrap().modified().unwrap();
        write_folder_meta(&dir, &server).unwrap();
        let mtime2 = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2);

        let _ = fs::remove_dir_all(&dir);
    }
}
